#--------------------------------------------------------------
# Name ------- Zara Malik
# Course ----- CS3233-01
# Project ---- Awesome Sauce
# Due date --- November 1, 2024
# This is the Makefile to build the Awesome Sauce project
#--------------------------------------------------------------

a.out: awesomeSauce.cpp camera.cpp camera.h
	g++ awesomeSauce.cpp camera.cpp -lglut -lGL -lGLU
clean:
	rm -f a.out
