
#-----------------------------------------------------------------------
# Name-------Zara Malik
# Course-----CS3233-01
# Project----Lighted Scene
# Due date --October 23, 2024
# This Makefile builds the application for the 3D lighted scene
#-----------------------------------------------------------------------

a.out: lightedScene.cpp camera.cpp camera.h
	g++ lightedScene.cpp camera.cpp -lglut -lGL -lGLU
clean:
	rm -f a.out
