#-----------------------------------------------------------------------
# Name-------Zara Malik
# Course-----CS3233-01
# Project----Exam 2- Take That!
# Due--------November 13, 2024
# This Makefile builds the application for the dartboard exam project
#-----------------------------------------------------------------------

a.out: takethat.cpp camera.cpp camera.h
	g++ takethat.cpp camera.cpp -lglut -lGL -lGLU
clean:
	rm -f a.out
