#-----------------------------------------------------------------------
# Name-------Zara Malik
# Course-----CS3233-01
# Project----Turn! Turn! Turn!
# Due--------November 22, 2024
# This Makefile builds the application for the object file project
#-----------------------------------------------------------------------

a.out: turn.cpp camera.cpp camera.h
	g++ turn.cpp camera.cpp -lglut -lGL -lGLU
clean:
	rm -f a.out
