#-----------------------------------------------------------------------
# Name-------Zara Malik
# Course-----CS3233-01
# Project----Draw Your House
# Due--------September 11, 2024
# This Makefile builds the application for the 3D octagonal bipyramid.
#-----------------------------------------------------------------------

a.out: bipyramid.cpp camera.cpp camera.h
	g++ bipyramid.cpp camera.cpp -lglut -lGL -lGLU
clean:
	rm -f a.out
