#-----------------------------------------------------------------------
# Name-------Zara Malik
# Course-----CS3233-01
# Project----Draw Your House
# Due--------September 11, 2024
# This Makefile builds the application for the Draw Your House project.
#-----------------------------------------------------------------------

a.out: myHouse.cpp
	g++ myHouse.cpp -lglut -lGL -lGLU
clean:
	rm -f a.out
