#-----------------------------------------------------------------------
# Name-------Zara Malik
# Course-----CS3233-01
# Project----Lighted Prism
# Due--------October 14, 2024
# This Makefile builds the application for the 3D lighted prism
#-----------------------------------------------------------------------

a.out: lightedPrism.cpp camera.cpp camera.h
	g++ lightedPrism.cpp camera.cpp -lglut -lGL -lGLU
clean:
	rm -f a.out
